services:
  redis:
    container_name: redis
    image: "valkey/valkey:latest"
    command: valkey-server
    ports:
      - "6379:6379"
    networks:
      - provider_net

  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tugascript"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - provider_net

networks:
  provider_net:
    driver: bridge
