//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::BlogReactionsEnum;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_post_comment_reaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_post_comment_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub created_by_id: i32,
    pub reaction: BlogReactionsEnum,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blog_post_comment::Entity",
        from = "Column::BlogPostCommentId",
        to = "super::blog_post_comment::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BlogPostComment,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::blog_post_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostComment.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
