//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_by_id: i32,
    pub cover_image_url: Option<String>,
    pub first_published_at: Option<DateTime>,
    pub published_at: Option<DateTime>,
    pub is_published: bool,
    pub is_featured: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blog_post_comment::Entity")]
    BlogPostComment,
    #[sea_orm(has_many = "super::blog_post_image::Entity")]
    BlogPostImage,
    #[sea_orm(has_many = "super::blog_post_reaction::Entity")]
    BlogPostReaction,
    #[sea_orm(has_many = "super::blog_post_tag::Entity")]
    BlogPostTag,
    #[sea_orm(has_many = "super::blog_post_technology::Entity")]
    BlogPostTechnology,
    #[sea_orm(has_many = "super::blog_series_post::Entity")]
    BlogSeriesPost,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::blog_post_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostComment.def()
    }
}

impl Related<super::blog_post_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostImage.def()
    }
}

impl Related<super::blog_post_reaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostReaction.def()
    }
}

impl Related<super::blog_post_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostTag.def()
    }
}

impl Related<super::blog_post_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostTechnology.def()
    }
}

impl Related<super::blog_series_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeriesPost.def()
    }
}

impl Related<super::blog_series::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_series_post::Relation::BlogSeries.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_series_post::Relation::BlogPost.def().rev())
    }
}

impl Related<super::technology::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_post_technology::Relation::Technology.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_post_technology::Relation::BlogPost.def().rev())
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_post_reaction::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_post_reaction::Relation::BlogPost.def().rev())
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        let current_time = Utc::now().naive_utc();
        self.updated_at = ActiveValue::Set(current_time);
        if insert {
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
