//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_series_post")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_series_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_post_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blog_post::Entity",
        from = "Column::BlogPostId",
        to = "super::blog_post::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BlogPost,
    #[sea_orm(
        belongs_to = "super::blog_series::Entity",
        from = "Column::BlogSeriesId",
        to = "super::blog_series::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BlogSeries,
}

impl Related<super::blog_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPost.def()
    }
}

impl Related<super::blog_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeries.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        if insert {
            let current_time = Utc::now().naive_utc();
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
