//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_series")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub subtitle: Option<String>,
    pub cover_image_url: Option<String>,
    pub created_by_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blog_series_post::Entity")]
    BlogSeriesPost,
    #[sea_orm(has_many = "super::blog_series_technology::Entity")]
    BlogSeriesTechnology,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::blog_series_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeriesPost.def()
    }
}

impl Related<super::blog_series_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeriesTechnology.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::blog_post::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_series_post::Relation::BlogPost.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_series_post::Relation::BlogSeries.def().rev())
    }
}

impl Related<super::technology::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_series_technology::Relation::Technology.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::blog_series_technology::Relation::BlogSeries
                .def()
                .rev(),
        )
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        let current_time = Utc::now().naive_utc();
        self.updated_at = ActiveValue::Set(current_time);
        if insert {
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
