//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_series_technology")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_series_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub technology_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blog_series::Entity",
        from = "Column::BlogSeriesId",
        to = "super::blog_series::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BlogSeries,
    #[sea_orm(
        belongs_to = "super::technology::Entity",
        from = "Column::TechnologyId",
        to = "super::technology::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Technology,
}

impl Related<super::blog_series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeries.def()
    }
}

impl Related<super::technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Technology.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
