//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::BlogReactionsEnum;
use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_post_reaction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_post_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub created_by_id: i32,
    pub reaction: BlogReactionsEnum,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blog_post::Entity",
        from = "Column::BlogPostId",
        to = "super::blog_post::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BlogPost,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::blog_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPost.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        if insert {
            let current_time = Utc::now().naive_utc();
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
