//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "related_technology")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent_technology_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_technology_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::technology::Entity",
        from = "Column::ChildTechnologyId",
        to = "super::technology::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Technology2,
    #[sea_orm(
        belongs_to = "super::technology::Entity",
        from = "Column::ParentTechnologyId",
        to = "super::technology::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Technology1,
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        if insert {
            let current_time = Utc::now().naive_utc();
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
