//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "blog_reactions_enum"
)]
pub enum BlogReactionsEnum {
    #[sea_orm(string_value = "hate")]
    Hate,
    #[sea_orm(string_value = "dislike")]
    Dislike,
    #[sea_orm(string_value = "ok")]
    Ok,
    #[sea_orm(string_value = "like")]
    Like,
    #[sea_orm(string_value = "love")]
    Love,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "code_source_enum")]
pub enum CodeSourceEnum {
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "gitlab")]
    Gitlab,
    #[sea_orm(string_value = "crates_io")]
    CratesIo,
    #[sea_orm(string_value = "npm")]
    Npm,
    #[sea_orm(string_value = "pypi")]
    Pypi,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "project_link_type_enum"
)]
pub enum ProjectLinkTypeEnum {
    #[sea_orm(string_value = "website")]
    Website,
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "gitlab")]
    Gitlab,
    #[sea_orm(string_value = "dev_to")]
    DevTo,
    #[sea_orm(string_value = "linkedin")]
    Linkedin,
    #[sea_orm(string_value = "youtube")]
    Youtube,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "project_status_enum"
)]
pub enum ProjectStatusEnum {
    #[sea_orm(string_value = "ongoing")]
    Ongoing,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "maintenance")]
    Maintenance,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "on_hold")]
    OnHold,
    #[sea_orm(string_value = "dropped")]
    Dropped,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "technology_type_enum"
)]
pub enum TechnologyTypeEnum {
    #[sea_orm(string_value = "language")]
    Language,
    #[sea_orm(string_value = "framework")]
    Framework,
    #[sea_orm(string_value = "database")]
    Database,
    #[sea_orm(string_value = "platform")]
    Platform,
    #[sea_orm(string_value = "tool")]
    Tool,
    #[sea_orm(string_value = "other")]
    Other,
}
