//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::TechnologyTypeEnum;
use chrono::Utc;
use sea_orm::{ActiveValue, ConnectionTrait, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "technology")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub icon: String,
    pub tech_type: TechnologyTypeEnum,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_by_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blog_post_technology::Entity")]
    BlogPostTechnology,
    #[sea_orm(has_many = "super::blog_series_technology::Entity")]
    BlogSeriesTechnology,
    #[sea_orm(has_many = "super::project_technology::Entity")]
    ProjectTechnology,
    #[sea_orm(has_many = "super::skill::Entity")]
    Skill,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::blog_post_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogPostTechnology.def()
    }
}

impl Related<super::blog_series_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogSeriesTechnology.def()
    }
}

impl Related<super::project_technology::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTechnology.def()
    }
}

impl Related<super::skill::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Skill.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::blog_post::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_post_technology::Relation::BlogPost.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::blog_post_technology::Relation::Technology
                .def()
                .rev(),
        )
    }
}

impl Related<super::blog_series::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_series_technology::Relation::BlogSeries.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::blog_series_technology::Relation::Technology
                .def()
                .rev(),
        )
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_technology::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_technology::Relation::Technology.def().rev())
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C: ConnectionTrait>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> {
        let current_time = Utc::now().naive_utc();
        self.updated_at = ActiveValue::Set(current_time);
        if insert {
            self.created_at = ActiveValue::Set(current_time);
        }
        Ok(self)
    }
}
